### ISSUE TITLE
Fixing corrupted boot volume after wakeup

### ISSUE THREAD

**Issue by LPhil** [dukzcry/osx-goodies#10]
There is some comment because of corrupted boot volume after sleep (wakeup).

SASMegaRAID.cpp
  506    /* XXX: Prevent sleep as it corrupts booting volume */

Where exactly is the problematic? Is there more detailed information?
Thx

**Comment by dukzcry** [comment]
Unfortunately, I don't know where the problem is and have no more information. That's why XXX
You can set `AllowSleep` to `true` in kext plist and check whether you have such issue at all
