### ISSUE TITLE
Support for ASUS Pike 2 3008-8i

### ISSUE THREAD

**Issue by Sideflare** [dukzcry/osx-goodies#6]
Forgive my ignorance. Will this work with my raid card?
I believe my card is of the mega raid family. 
I am working on project 8 bay Sata 3 Mac Pro 5,1 12 core Delight, and i am looking primarily for sata 3 support. Much to my dismay i discovered my model number mac pro did away with the onboard mini sas connector and so i purchased an ASUS Pike 2 3008-8i on an incredible new egg deal for around $100! the card appears to be awesome, should suit my needs with 2x onboard mini sas hd connectors. i piggybacked the onboard power with splitters and connected a fan out cable. makeshift bay duplicator. 

i was unable to save the installer file to try it. it saved as html. i renamed it app. no bueno. please assist. 

feel free to share this with anyone on insanely mac or other location. if will help someone else with similar goals.

**Comment by dukzcry** [comment]
Unfortunately no. Your card belongs to Fusion-MPT generation which is not supported by this kext.

**Comment by Sideflare** [comment]
:-(  do you know of any other options to utilize this card on my mac pro even if it's only for SATA functionality? I really like that it has to internal mini-sas HD connectors

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Jun 28, 2016 at 7:26 AM -0600, "A. V. Lukyanov" <notifications@github.com<mailto:notifications@github.com>> wrote:


Unfortunately no. Your card belongs to Fusion-MPT generation which is not supported by this kext.

-

**Comment by dukzcry** [comment]
Not that I know of :(
