### ISSUE TITLE
macOS Sierra support for LSI-9260-8i ?

### ISSUE THREAD

**Issue by wmjlxl** [dukzcry/osx-goodies#7]
Hello dukzcry,

upgraded my osx from 10.11.6 to 10.12 macos sierra, and now my LSi-9260-8i works but my macos cannot sleep anymore.

any fix driver ?  thanks

**Comment by dukzcry** [comment]
Hi wmjlxl,

Do you use a kext from "Unsafe sleep enabled.zip"? Because it's the only one that had sleep working.
