### ISSUE TITLE
 Only chipsets starting from ICH5 are supported

### ISSUE THREAD

**Issue by csekel** [dukzcry/osx-goodies#8]
Can we get IC supported for newer chipsets? We could use it for PureDarwin.

**Comment by dukzcry** [comment]
@csekel Sorry, can't help with that. I've left Mac scene a long time ago.

**Comment by csekel** [comment]
Any chance you'd come back?

**Comment by dukzcry** [comment]
Not likely, don't even have Darwin/macOS compatible hardware atm ¯\_(ツ)_/¯
BTW I wish you a great success with PureDarwin :+1:
